---
- name: Patch Test on Servers
  hosts: test2
  tasks:
    - name: Update Cache
      apt:
        update_cache: yes
        cache_valid_time: 86400 # 1 day

    - name: List all the Upgradable Packages via apt list --upgradable
      shell: apt list --upgradable |grep -v "Listing" | awk -F " " '{print $1 ":" $2}'
      register: list1

    - name: Print the list obtained from above command
      debug:
        msg: "{{ list1.stdout_lines }}"

    - name: List all the Upgradable Packages via apt-get -s dist-upgrade
      shell: apt-get -s dist-upgrade | grep "Inst" | awk -F " " '{print $2}'
      register: list2

    - name: Print the list obtained from above command
      debug:
        msg: "{{ list2.stdout_lines }}"
        
# Update only one package
    - name: Install app
      apt:
         name: "{{ list2.stdout_lines[0] }}"
         state: present